# This is a basic workflow to help you get started with Actions

name: Update Language Source

# Controls when the action will run. 
on:
  schedule:
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Update Language Source
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $defaultBranch = (gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/foundryvtt/dnd5e | ConvertFrom-Json).default_branch
          iwr "https://github.com/foundryvtt/dnd5e/raw/$defaultBranch/lang/en.json" | % { if ($_.StatusCode -eq 200) { $_.Content > ./.github/en.json } }
        
      - name: Add & Commit
        uses: EndBug/add-and-commit@v7.2.1
        with:
          add: ".github/en.json"
          branch: main
